### ISSUE TITLE
python小白，不清楚为什么报错了

### ISSUE THREAD

**Issue by 1974148797** [Alkaid-C/BBDown-BilibiliAutoFollowDownloader#1]
Traceback (most recent call last):
  File "D:\tools\BBDown-BilibiliAutoFollowDownloader-main\BilibiliAutoFollowDownloader.py", line 197, in <module>
    main()
  File "D:\tools\BBDown-BilibiliAutoFollowDownloader-main\BilibiliAutoFollowDownloader.py", line 182, in main
    DownloadList=GetDownLoadList()
  File "D:\tools\BBDown-BilibiliAutoFollowDownloader-main\BilibiliAutoFollowDownloader.py", line 159, in GetDownLoadList    if NewVideoList[i] not in CurVideoList:
IndexError: list index out of range

**Comment by 1974148797** [comment]
哦 我拿chatgpt改了一下可以了   我以为是重复执行一直监测up主是否更新然后下载 ，原来是在执行后检查一次up是否更新然后下载，之后程序结束 orz
